### PR TITLE
2015 Event Update

### PR DESCRIPTION
**Pull request by robdudley**
Updated the St. Helier page to include details of upcoming event and add some more info about past event.

Plus a robot ... you have to have a robot right?

R

### CODE REVIEW

**Comment by michaeldupuisjr** [comment]
I may be out of the lingo loop on this, but did you guys want it to say "Communituy" on the image?

**Comment by robdudley** [comment]
Haha,

No, no we don't (bloody graphic designers can't spell).

I'll get it updated shortly and add to the PR.

Well spotted thanks!

Rob

Michael Dupuis wrote:
> I may be out of the lingo loop on this, but did you guys want it to say
> "Communituy" on the image?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenHack/openhack.github.com/pull/315#issuecomment-70828684>.
> 

-- 

Rob Dudley
+44 (0) 7797 813386
rob@rcwd.me
www.rcwd.me

**Comment by robdudley** [comment]
Ok PR updated with corrected logo.

Thanks

**Comment by michaeldupuisjr** [comment]
Thanks @robdudley!

**Pull request merged**
