### PR TITLE
Commit update to branch

### PR DESCRIPTION
**Pull request by shrinkray**
Apply markdown fixes to formatting and content. Improve readability and quality of the content.

### CODE REVIEW

**Comment by friedger** [comment]
Could you please send a new pr?

**Comment by shrinkray** [comment]
Hello Friedger, Thank you for your assistance on my request. Please apply our latest content commits.

**Comment by friedger** [comment]
@shrinkray could you please verify that the text is now correct. There were concurrent edits and I hope I picked the right ones. 

You can also directly edit on the OpenHack:master website. github will deal with cloning and pull requesting..

**Comment by shrinkray** [comment]
@friedger I do need to make changes, something is not right. Once I make a change, are you saying that I do not need a Pull Request (pr) for it to be updated?

**Comment by friedger** [comment]
Pull request are still needed, but it is just a button click away if you
edit on github directly

Am 21.12.2016 00:01 schrieb "Greg Miller" <notifications@github.com>:

**Pull request merged**
