### PR TITLE
Add OpenHack Haverhill, MA

### PR DESCRIPTION
**Pull request by johnnadeau**
I've added a listing for OpenHack in Haverhill, MA. 

This is part of an established meetup group known as the [Haverhill Hackers](http://www.meetup.com/HaverhillHackers/).

### CODE REVIEW

**Comment by abargnesi** [comment]
Ah good point.

**Comment by abargnesi** [comment]
:+1:

Really grateful to participate in the OpenHack community.

**Comment by abargnesi** [comment]
@duggiefresh Could you review this?

Thanks!

**Comment by duggiefresh** [comment]
LGTM! Thanks for your contributions @abargnesi and @johnnadeau ! Hope you both have a blast!

**Comment by johnnadeau** [comment]
Thanks! :+1:

**Pull request merged**
